include: package:very_good_analysis/analysis_options.yaml

formatter:
  trailing_commas: preserve

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  
  errors: 
    invalid_annotation_target: false

  exclude:
    - bricks/**
    - '**/*.g.dart'
    - '**/*.config.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    #- '**/*.gr.dart'

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
    public_member_api_docs: false
    directives_ordering: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    specify_nonobvious_property_types: false